#!python file type
import os
app_env = Environment(CPPPATH = ".", CFLAGS="-g", ENV = dict(PATH=os.environ["PATH"]))
app_env.ParseConfig("pkg-config --cflags --libs gtk+-3.0")

target = app_env["TARGET_OS"]
if target is not None and target.startswith("win"):
    app_env.Append(LINKFLAGS="-Wl,--export-all-symbols")
else:
    app_env.Append(LINKFLAGS="-Wl,--export-dynamic")

main_program = app_env.Program(target = "charmake", source = ["proj.c"])
